version: '3'

services:
  services-db:
    image: postgres:10.9-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: services_local

  services-app:
    container_name: services-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    links:
      - services-db
    environment:
      DATABASE_URL: postgres://postgres:password@services-db/services_local
      SECRET_KEY_BASE: key-base
      MIX_ENV: prod
